apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: danstaken/smithe-backend-do:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: PIDGTM_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: PIDGTM_DATABASE_URL
          - name: STARTGG_TOKEN
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: STARTGG_TOKEN
          - name: STARTGG_TOKEN_1
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: STARTGG_TOKEN_1
          - name: STARTGG_TOKEN_2
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: STARTGG_TOKEN_2
          - name: STARTGG_TOKEN_3
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: STARTGG_TOKEN_3
          - name: STARTGG_TOKEN_4
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: STARTGG_TOKEN_4
          - name: STARTGG_TOKEN_5
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: STARTGG_TOKEN_5
          - name: STARTGG_TOKEN_6
            valueFrom:
              secretKeyRef:
                name: backend-secrets-multiple-tokens
                key: STARTGG_TOKEN_6
